# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
ci:
  autoupdate_schedule: quarterly
  skip: ["identity", "cargo-check", "cargo-fmt", "cargo-test"]

default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["pre-commit"]

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
#      - id: no-commit-to-branch
#        args: ["--branch", "main"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: detect-private-key

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config

  - repo: https://github.com/billwallis/bills-hooks
    rev: v0.0.15
    hooks:
      - id: banned-python-code
      - id: check-no-commit-comment
      - id: tidy-gitkeep

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.2
    hooks:
      - id: check-github-workflows
      - id: check-compose-spec

  - repo: local
    hooks:
      - &cargo-default
        id: cargo-check
        name: Check Rust files can compile
        entry: cargo check
        stages: ["pre-commit", "pre-push"]
        language: system
        pass_filenames: false
        always_run: true
      - <<: *cargo-default
        id: cargo-fmt
        name: Format Rust files
        entry: cargo fmt
      - <<: *cargo-default
        id: cargo-test
        name: Run unit tests
        entry: cargo test --verbose
        stages: ["pre-push"]
