# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Tests
run-name: Tests 🧪

on:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo test --verbose
